Entity/Presentation.php
<?php

namespace Netgen\LiveVotingBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Presentation
 */
class Presentation
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $presenterName;

    /**
     * @var string
     */
    private $presenterSurname;

    /**
     * @var string
     */
    private $presentationName;

    /**
    * @var text
    */
    private $description;

    /**
     * @var boolean
     */
    private $votingEnabled = false;

    private $joind_in_id = null;

    /**
     * @return null
     */
    public function getJoindInId()
    {
        return $this->joind_in_id;
    }

    /**
     * @param null $joind_in_id
     */
    public function setJoindInId($joind_in_id)
    {
        $this->joind_in_id = $joind_in_id;
    }



    /**
     * @return mixed
     */
    public function getGlobalBrake()
    {
        return $this->globalBrake;
    }

    /**
     * @param mixed $globalBrake
     */
    public function setGlobalBrake($globalBrake)
    {
        $this->globalBrake = $globalBrake;
    }

    /**
     * @var boolean
     */
    private $globalBrake = false;


    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $vote;

    /**
     * @var \Netgen\LiveVotingBundle\Entity\Event
     */
    private $event;
    private $user;

    private $country = '';
    /**
     * @var string
     */
    private $image;

    private $hall;

    private $presentationComments;

    /**
     * Constructor
     */

    public function __construct()
    {
        $this->vote = new \Doctrine\Common\Collections\ArrayCollection();
        $this->presentationComments = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    public function setId($id){
        return $this->id = $id;
    }

    /**
     * Set presenterName
     *
     * @param string $presenterName
     * @return Presentation
     */
    public function setPresenterName($presenterName)
    {
        $this->presenterName = $presenterName;

        return $this;
    }

    /**
     * Get presenterName
     *
     * @return string
     */
    public function getPresenterName()
    {
        return $this->presenterName;
    }

    /**
     * Set presenterSurname
     *
     * @param string $presenterSurname
     * @return Presentation
     */
    public function setPresenterSurname($presenterSurname)
    {
        $this->presenterSurname = $presenterSurname;

        return $this;
    }

    /**
     * Get presenterSurname
     *
     * @return string
     */
    public function getPresenterSurname()
    {
        return $this->presenterSurname;
    }

    /**
     * Set presentationName
     *
     * @param string $presentationName
     * @return Presentation
     */
    public function setPresentationName($presentationName)
    {
        $this->presentationName = $presentationName;

        return $this;
    }

    /**
     * Get presentationName
     *
     * @return string
     */
    public function getPresentationName()
    {
        return $this->presentationName;
    }

    /**
     * Set votingEnabled
     *
     * @param boolean $votingEnabled
     * @return Presentation
     */
    public function setVotingEnabled($votingEnabled)
    {
        $this->votingEnabled = $votingEnabled;

        return $this;
    }

    /**
     * Get votingEnabled
     *
     * @return boolean
     */
    public function getVotingEnabled()
    {
        return $this->votingEnabled;
    }

    /**
     * Add vote
     *
     * @param \Netgen\LiveVotingBundle\Entity\Vote $vote
     * @return Presentation
     */
    public function addVote(\Netgen\LiveVotingBundle\Entity\Vote $vote)
    {
        $this->vote[] = $vote;

        return $this;
    }

    /**
     * Remove vote
     *
     * @param \Netgen\LiveVotingBundle\Entity\Vote $vote
     */
    public function removeVote(\Netgen\LiveVotingBundle\Entity\Vote $vote)
    {
        $this->vote->removeElement($vote);
    }

    /**
     * Get vote
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getVote()
    {
        return $this->vote;
    }

    /**
     * Set event
     *
     * @param \Netgen\LiveVotingBundle\Entity\Event $event
     * @return Presentation
     */
    public function setEvent(\Netgen\LiveVotingBundle\Entity\Event $event = null)
    {
        $this->event = $event;

        return $this;
    }

    /**
     * Get event
     *
     * @return \Netgen\LiveVotingBundle\Entity\Event
     */
    public function getEvent()
    {
        return $this->event;
    }

    public function setUser (\Netgen\LiveVotingBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $votes;


    /**
     * Get votes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getVotes()
    {
        return $this->votes;
    }

    public function setCountry($country)
    {
        $this->country = $country;
    }


    public function getCountry()
    {
        return $this->country;
    }

    public function setImage($image = null)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

    private $begin;
    private $end;

    public function setBegin($begin)
    {
        $this->begin = $begin;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getBegin()
    {
        return $this->begin;
    }

    public function setEnd($end)
    {
        $this->end = $end;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getEnd()
    {
        return $this->end;
    }

    public function setHall($hall)
    {
        $this->hall = $hall;
    }
    public function getHall()
    {
        return $this->hall;
    }

    public function getAbsolutePath()
    {
        return null === $this->image
            ? null
            : $this->getUploadRootDir().'/'.$this->getImageName();
    }

    public function getWebPath()
    {
        return null === $this->image
            ? null
            : $this->getUploadDir().'/'.$this->getImage();
    }

    public function getHashedImageName(){
        return md5(
            $this->getPresenterName().
            $this->getPresenterSurname().
            $this->getId().
            $this->getPresentationName()
        );
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/bundles/livevoting/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'img/faces';
    }


    public function upload()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getImage()) {
            return;
        }
        if(is_string($this->getImage())) return;

        // use the original file name here but you should
        // sanitize it at least to avoid any security issues

        // move takes the target directory and then the
        // target filename to move to
        $new_name = $this->getHashedImageName().'.'.$this->getImage()->guessExtension();
        $this->getImage()->move(
            $this->getUploadRootDir(),
            $new_name
        );

        // set the path property to the filename where you've saved the file
        $this->image = $new_name;
    }



    /**
     * Set description
     *
     * @param string $description
     * @return Presentation
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add presentationComments
     *
     * @param \Netgen\LiveVotingBundle\Entity\PresentationComment $presentationComments
     * @return Presentation
     */
    public function addPresentationComment(\Netgen\LiveVotingBundle\Entity\PresentationComment $presentationComments)
    {
        $this->presentationComments[] = $presentationComments;

        return $this;
    }

    /**
     * Remove presentationComments
     *
     * @param \Netgen\LiveVotingBundle\Entity\PresentationComment $presentationComments
     */
    public function removePresentationComment(\Netgen\LiveVotingBundle\Entity\PresentationComment $presentationComments)
    {
        $this->presentationComments->removeElement($presentationComments);
    }

    /**
     * Get presentationComments
     *
     * @return ArrayCollection
     */
    public function getPresentationComments()
    {
        return $this->presentationComments;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $presentationImages;


    /**
     * Add presentationImages
     *
     * @param \Netgen\LiveVotingBundle\Entity\PresentationImage $presentationImages
     * @return Presentation
     */
    public function addPresentationImage(\Netgen\LiveVotingBundle\Entity\PresentationImage $presentationImages)
    {
        $this->presentationImages[] = $presentationImages;

        return $this;
    }

    /**
     * Remove presentationImages
     *
     * @param \Netgen\LiveVotingBundle\Entity\PresentationImage $presentationImages
     */

Form/PresentationType.php
<?php

namespace Netgen\LiveVotingBundle\Form;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PresentationType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text' ,array('attr' => array('class' => 'form-control')))
            ->add('description', 'textarea' ,array('attr' => array('class' => 'form-control', 'rows' => "7")))
            ->add('image_url', 'file', array(
                'data_class' => null,
                'required' => false
            ))
            ->add('globalBrake', 'checkbox', array('attr' => array('class' => 'form-control'), "label" => "Global break (lunch, pause, etc.)", 'required' => false))
            ->add('hall', 'text' ,array('attr' => array('class' => 'form-control')))
            ->add('begin', 'datetime', array(
                "years" => range(date('Y') - 0, date('Y') + 5)
            ))
            ->add('end', 'datetime', array(
                "years" => range(date('Y') - 0, date('Y') + 5)
            ))
            ->add('joind_in_id', 'text', array('attr' => array('class' => 'form-control'), 'required' => false))
            //->add('event', 'entity', array('class'=>'Netgen\LiveVotingBundle\Entity\Event', 'disabled'=>true))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Netgen\LiveVotingBundle\Service\PresentationService\Record\PresentationRecord',
            'attr' => array('style'=>'width:300px;margin-left:10px;', 'role'=>'form')
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'netgen_livevotingbundle_presentation';
    }
}

Resources/views/Presentation/edit.html.twig
{% extends 'LiveVotingBundle::baseAdmin.html.twig' %}

{% block title %}Edit|Presentation|LiveVoting{% endblock %}
{% block mainHeading %}Edit presentation{% endblock %}

{% block body -%}
    <div class="row">
        <div class="col-xs-12 col-sm-4 margin-top">
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_label(form.presenterName) }}
                {{ form_widget(form.presenterName) }}
            </div>
            <div class="form-group">
                {{ form_label(form.presenterSurname) }}
                {{ form_widget(form.presenterSurname) }}
            </div>
            <div class="form-group">
                {{ form_widget(form.presentationRecord) }}
            </div>
            <div class="form-group">
                {{ form_label(form.user) }}
                {{ form_widget(form.user) }}
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="row secondary-footer">
        <div class="col-xs-12">
            <a href="{{ path('admin_presentation', {'event_id':entity.getEventId} ) }}"><button type="button" class="btn">Back</button></a>
        </div>
    </div>

{% endblock %}

Resources/views/Presentation/index.html.twig
{% extends 'LiveVotingBundle::baseAdmin.html.twig' %}

{% block title %}Presentations|LiveVoting{% endblock %}

{% block mainHeading %}Presentations: {{ event.name }} - {{ event.stateName }}{% endblock %}

{% block body -%}
    {% for flashMessage in app.Session.flashbag.get('message') %}
    <div class="alert alert-danger">
        <div class="text">{{flashMessage}}</div>
    </div>
    {% endfor %}

    <div class="row">
        <div class="col-xs-12">
            <table id="view-presentations" class="records_list table margin-top">
                <thead>
                    <tr>
                        <th></th>
                        <th>Presentation</th>
                        <th>Presenter</th>
                        <th>Voting status</th>
                        <th>Joind.in</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                {% for entity in entities %}
                    <tr>
                        <td><img width="40px" class="image-o" src='{{ asset('bundles/livevoting/' ~ ((entity[0].getImageUrl) ? entity[0].getImageUrl : 'img/assets/angry-che.png')) }}'/></td>

                        <td>{{ entity[0].name }}</td>
                        <td>{{ entity[0].presenterName }} {{ entity[0].presenterSurname }}</td>
                        <td>{{ form(entity[1]) }}</td>
                        <td>{{ entity[0].joindInId }}</td>
                        <td>
                            <a href="{{ path('admin_presentation_edit', { 'id': entity[0].id }) }}"><button type="button" class="btn">Edit</button></a>
                        </td>
                        <td>
                            <a href="{{ path('admin_presentation_delete', { 'id': entity[0].id }) }}"><button type="button" class="btn icon"><i class="fa fa-lg fa-times"></i></button></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row secondary-footer">
        <div class="col-xs-12">
            <button type="button" id="publishPresentationButton" onclick="publishPresentations()" data-success-text="Publishing successful" data-loading-text="Publishing..." class="btn" autocomplete="off">Publish presentations</button>
            <label>
                <select id="joind-events-select" class="form-control">
                    {% for event in joindInEvents %}
                        <option value="{{ event.joindInId }}">{{ event.name }}</option>
                    {% endfor %}
                </select>
            </label>
            <div class="clearfix"></div>
            <a href="{{ path('admin_event') }}"><button type="button" class="btn">Back</button></a>
            <a href="{{ path('admin_presentation_new', {'event_id':event.getId}) }}"><button type="button" class="btn"><i class="fa fa-plus"></i> Add presentation</button></a>
        </div>
    </div>
{% endblock %}

{#
{% block javascripts %}
    <script type="text/javascript">
        function publishPresentations() {
            var button = $("#publishPresentationButton");
            button.button('loading');
            button.prop("disabled",true);
            $.ajax({
                headers: {
                    'Authorization': 'Bearer {{ joind_in_access_token }}'
                },
                'type': 'post',
                'url': '{{ url('admin_presentation_publish', {'event_id': event.id}) }}',
                'data': {joindEvent: $("#joind-events-select").val()},
                success: function (data) {
                    button.button('success');
                },
                error: function (e) {
                    alert(e.responseJSON.error);
                    button.button('reset');
                    button.prop("disabled",false);
                }
            });
        }
    </script>
{% endblock %}
#}

Resources/views/Presentation/new.html.twig
{% extends 'LiveVotingBundle::baseAdmin.html.twig' %}

{% block title %}New|Presentation|LiveVoting{% endblock %}
{% block mainHeading %}New presentation{% endblock %}

{% block body -%}
    <div class="row">
        <div class="col-xs-12 col-sm-4 margin-top">
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_label(form.presenterName) }}
                {{ form_widget(form.presenterName) }}
            </div>
            <div class="form-group">
                {{ form_label(form.presenterSurname) }}
                {{ form_widget(form.presenterSurname) }}
            </div>
            <div class="form-group">
                {{ form_widget(form.presentationRecord) }}
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="row secondary-footer">
        <div class="col-xs-12">
            <a href="{{ path('admin_presentation', {'event_id':event_id} ) }}"><button type="button" class="btn">Back</button></a>
        </div>
    </div>
{% endblock %}

Resources/views/Presentation/user.html.twig
{% extends 'LiveVotingBundle::base.html.twig' %}

{% block title %}Presentations|User|LiveVoting{% endblock %}

{% block body -%}
    <div class="row">
        <div class="col-xs-12 box light shadow" style="background-image: url({{asset('bundles/livevoting/img/assets/lectures-bg.png')}});">
            <div class="row vertical-align-xs">
                <div class="col-xs-4 col-sm-1 text-center icon">
                    <i class="fa fa-clipboard"></i>
                </div>
                <div class="col-xs-8 col-sm-6 col-lg-7 text-wrapper extra-margin">
                    <div>
                        <h2>My lectures</h2>
                    </div>
                    <div>
                        <label class="big">Edit Your lectures</label>
                    </div>
                </div>
                <div class="clearfix visible-xs"></div>
                <div class="col-xs-12 col-sm-5 col-lg-4">
                    <div class="text-right actions single-action master">
                        <a href="{{ path('user_landing') }}" class="text-center"><i class="fa fa-chevron-circle-left"></i><span class="hidden-sm">Events</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% for flashMessage in app.Session.flashbag.get('message') %}
      <div class="row flash-messages">
          <div class="col-xs-12">
            <h3><i class="fa fa-lg fa-info-circle"></i>{{flashMessage}}</h3>
          </div>
      </div>
    {% endfor %}

    <div class="row">
        {% for entity in entities %}
        <div class="col-xs-12 box shadow">
            <div class="row vertical-align-xs">
                <div class="col-xs-4 col-sm-1">
                    <img class="image image-o" src="{{asset('bundles/livevoting/' ~ ((entity[0].getImageUrl) ? entity[0].getImageUrl : 'img/assets/angry-che.png') )}}">
                </div>
                <div class="col-xs-8 col-sm-6 col-lg-7 text-wrapper extra-margin">
                    <div>
                        <h2>{{ entity[0].name }}</h2>
                    </div>
                    <div class="description hidden-xs">
                        <span>{{ entity[0].hall }} <i class="fa fa-at"></i> {{ entity[0].begin|date('H:m') }}</span>
                        <span>Date: {{ entity[0].begin|date('d. F') }}</span>
                    </div>
                </div>
                <div class="clearfix visible-xs"></div>
                <div class="col-xs-12 visible-xs xs-description">
                    <span>{{ entity[0].hall }} <i class="fa fa-at"></i> {{ entity[0].begin|date('H:m') }}</span>
                    <span>Date: {{ entity[0].begin|date('d. F') }}</span>
                </div>
                <div class="clearfix visible-xs"></div>
                <div class="row">
                    <div class="col-xs-12 visible-xs full-description">
                        <h3>Lecture description</h3>
                        <p>{{ entity[0].description }}</p>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-5 col-lg-4">
                    <div class="text-right actions single-action">
                        <a href="{{ path('user_presentation_edit', { 'id': entity[0].id }) }}" class="text-center"><i class="fa fa-pencil"></i><span>Edit</span></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 hidden-xs full-description">
                    <h3>Lecture description</h3>
                    <p>{{ entity[0].description }}</p>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        {% endfor %}
    </div>
{% endblock %}

Resources/views/Presentation/useredit.html.twig
{% extends 'LiveVotingBundle::base.html.twig' %}

{% block title %}Edit|Presentation|User|LiveVoting{% endblock %}

{% block body -%}
  {% for flashMessage in app.Session.flashbag.get('message') %}
    <div class="row flash-messages">
        <div class="col-xs-12">
          <h3><i class="fa fa-lg fa-info-circle"></i>{{flashMessage}}</h3>
        </div>
    </div>
  {% endfor %}

    <div class="row">
        <div id="form-userpres" class="col-xs-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 form-container">
            {{ form_start(edit_form) }}

            <label>Edit presentation</label>

            <p>Presentation Name: <input type="text" value="{{ entity.name }}" disabled></p>

            <p>Presenter Name <input type="text" value="{{ entity.presenterName }}" disabled></p>

            <p>Presenter Surname <input type="text" value="{{ entity.presenterSurname }}" disabled></p>

            <div class="ext">
                {{ form_label(edit_form.description) }}
                {{ form_widget(edit_form.description) }}
            </div>

            <p>Hall <input type="text" value="{{ entity.hall }}" disabled></p>

            <p>Event <input type="text" value="{{ event.name }}" disabled></p>

            <p>Starts <input type="text" value="{{ entity.begin | date("i:H, m/d/Y") }}" disabled></p>

            <p>Ends <input type="text" value="{{ entity.end | date("i:H, m/d/Y") }}" disabled></p>

            {{ form_end(edit_form) }}
        </div>
    </div>
{% endblock %}